
/****** Object:  Database [InvestX_Archive]    Script Date: 2020-11-26 4:07:46 PM ******/
--USE [InvestX_Archive]
--GO

CREATE PROCEDURE [dbo].[CreatInvestX_ArchiveDB]	
AS


IF NOT(EXISTS(SELECT * FROM master.sys.sysdatabases WHERE name='InvestX_Archive'))
BEGIN

CREATE DATABASE [InvestX_Archive]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InvestX_Archive', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\InvestX_Archive.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InvestX_Archive_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\InvestX_Archive_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InvestX_Archive].[dbo].[sp_fulltext_database] @action = 'enable'
end
--GO

ALTER DATABASE [InvestX_Archive] SET ANSI_NULL_DEFAULT OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET ANSI_NULLS OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET ANSI_PADDING OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET ANSI_WARNINGS OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET ARITHABORT OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET AUTO_CLOSE OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET AUTO_SHRINK OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET AUTO_UPDATE_STATISTICS ON 
--GO

ALTER DATABASE [InvestX_Archive] SET CURSOR_CLOSE_ON_COMMIT OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET CURSOR_DEFAULT  GLOBAL 
--GO

ALTER DATABASE [InvestX_Archive] SET CONCAT_NULL_YIELDS_NULL OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET NUMERIC_ROUNDABORT OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET QUOTED_IDENTIFIER OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET RECURSIVE_TRIGGERS OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET  DISABLE_BROKER 
--GO

ALTER DATABASE [InvestX_Archive] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET DATE_CORRELATION_OPTIMIZATION OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET TRUSTWORTHY OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET ALLOW_SNAPSHOT_ISOLATION OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET PARAMETERIZATION SIMPLE 
--GO

ALTER DATABASE [InvestX_Archive] SET READ_COMMITTED_SNAPSHOT OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET HONOR_BROKER_PRIORITY OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET RECOVERY FULL 
--GO

ALTER DATABASE [InvestX_Archive] SET  MULTI_USER 
--GO

ALTER DATABASE [InvestX_Archive] SET PAGE_VERIFY CHECKSUM  
--GO

ALTER DATABASE [InvestX_Archive] SET DB_CHAINING OFF 
--GO

ALTER DATABASE [InvestX_Archive] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
--GO

ALTER DATABASE [InvestX_Archive] SET TARGET_RECOVERY_TIME = 60 SECONDS 
--GO

ALTER DATABASE [InvestX_Archive] SET DELAYED_DURABILITY = DISABLED 
--GO

ALTER DATABASE [InvestX_Archive] SET QUERY_STORE = OFF
--GO

ALTER DATABASE [InvestX_Archive] SET  READ_WRITE 
--GO
END

GO

IF NOT(EXISTS(SELECT * FROM master.sys.sysdatabases WHERE name='InvestX_Archive'))
BEGIN
 print('yws');
END
GO
